title: Settings
data:
  logo: jigar_updated-bg-(1).png
  site_name: "Jigar's Blog"
  meta_description: 'Personal blog of Jigar Dhulla - Sharing thoughts on PHP, Laravel, Livewire and Docker'
  og_image: jigar_updated-bg-(1).png
